language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"
before_script:
  - yarn
script: 
  - yarn build
deploy:
  provider: npm
  email: ${EMAIL}
  api_key: ${AUTH_TOKEN}
  skip_cleanup: true
  on:
    branch: master